name: "Terraform Format"
on:
  - pull_request
env:
  tf_version: 1.0.9
jobs:
 terraform_format:
    name: "Terraform Format"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform/
    steps:
      - name: "Checkout"
        uses: actions/checkout@master

      - name: 'Login via Azure CLI..'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      # - name: Executing Azure cli installation script
      #   run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      # - name: Authenticating to Azure Platform | az login
      #   run: az login --service-principal --username ${{ secrets.SERVICE_PRINCIPAL_CLIENT_ID }} --password ${{ secrets.SERVICE_PRINCIPAL_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
      
      - name: "Terraform Setup"
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.tf_version }}
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform version
        run: |
          terraform version
      
      - name: Terraform Init
        id: init
        run: terraform init

      - name: "Terraform Validate"
        id: validate
        run: terraform validate -no-color

      - name: "Terraform Format"
        id: fmt
        run: terraform fmt -check --recursive
      
      - name: "Terraform Plan"
        id: plan
        run: terraform plan -no-color
      
      - run: echo ${{ steps.plan.outputs.stdout }}
      - run: echo ${{ steps.plan.outputs.stderr }}
      - run: echo ${{ steps.plan.outputs.exitcode }}
